version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bbt_db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: {}